spring:
  application:
    name: pomina-erp

  profiles:
    active: dev

  threads:
    virtual:
      enabled: true

  logging:
    file:
      path: logs
      name: logs/app.log
    level:
      org.springframework.transaction: DEBUG
      org.mybatis.spring: DEBUG

mybatis:
  config-location: classpath:/mybatis/configuration/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/**/**/*.xml
  executor-type: batch