server:
  port: 8081
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  datasource:
    hikari:
      auto-commit: false
      maximum-pool-size: 30
      minimum-idle: 10
      initialization-fail-timeout: 0
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

    master:
      url: ${MASTER_DB_URL}
      username: ${MASTER_DB_USERNAME}
      password: ${MASTER_DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource

    slave:
      url: ${SLAVE_DB_URL}
      username: ${SLAVE_DB_USERNAME}
      password: ${SLAVE_DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 5000
      lettuce:
        pool:
          max-active: 200
          max-idle: 50
          min-idle: 10

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

security:
  jwt:
    access-token-expiration: 900000      # 15 phút
    refresh-token-expiration: 1296000000   # 15 ngày
    secret-key: ${JWT_SECRET_KEY}
  encryption:
    secret: ${ENCRYPTION_SECRET_KEY}

nominatim:
  email: minhnam1810@gmail.com
  url: https://nominatim.openstreetmap.org

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}
    geocoding-url: https://maps.googleapis.com/maps/api/geocode/json

vonage:
  api:
    key: c53321d0
    secret: nGXfHZxjpoj0ZNip

cloudinary:
  cloud-name: "dqqqjxnfh"
  api-key: "255558816145194"
  api_secret: "gfcwesLzyJVykvcuJIHctzOOuoU"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always