server:
  port: 8080

spring:
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1

  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000

    master:
      url: jdbc:mariadb://mariadb-master:3306/pomina_master_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Ho_Chi_Minh
#        url: jdbc:mariadb://maxscale:4006/pomina_master_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Ho_Chi_Minh
      username: root
      password: root123
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource

    slave:
      url: jdbc:mariadb://mariadb-slave:3306/pomina_slave_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Ho_Chi_Minh
      username: root
      password: root123
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource

security:
  jwt:
    access-token-expiration: 900000      # 15 phút
    refresh-token-expiration: 604800000   # 7 ngày
    secret-key: oB1Zvsn1261tfh0msDaGCP63l+rYq15F/O+ksyqZWe4qWqHRwvvz5pHs3qgHBhYi

nominatim:
  email: minhnam1810@gmail.com
  url: https://nominatim.openstreetmap.org

google:
  maps:
    api-key: AIzaSyDm-BhvvCnWOUKwQeLxRNSRcfesTssRIZI
    geocoding-url: https://maps.googleapis.com/maps/api/geocode/json

vonage:
  api:
    key: c53321d0
    secret: nGXfHZxjpoj0ZNip

logging:
  level:
    root: INFO
    com.pomina.erpapp: DEBUG
