spring:
  application:
    name: pomina-erp

  jackson:
    time-zone:
      Asia/Ho_Chi_Minh

  profiles:
    active: dev

  threads:
    virtual:
      enabled: true

  logging:
    file:
      path: logs
      name: logs/app.log
    level:
      root: INFO

mybatis:
  config-location: classpath:/mybatis/configuration/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/**/**/*.xml