spring:
  application:
    name: pomina-erp

  profiles:
    active: dev

  threads:
    virtual:
      enabled: true

  logging:
    file:
      path: logs
      name: logs/app.log
    level:
      org.apache.ibatis: DEBUG
      org.mybatis: DEBUG
      org.mybatis.spring: DEBUG
      org.springframework.jdbc.core: TRACE
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      org.springframework.boot.autoconfigure.security: DEBUG

mybatis:
  config-location: classpath:/mybatis/configuration/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/**/**/*.xml