server:
  port: 8089

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
    master:
      url: jdbc:mariadb://localhost:3306/pomina_master_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Ho_Chi_Minh
      username: root
      password: root123
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
    slave:
      url: jdbc:mariadb://localhost:3307/pomina_slave_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Ho_Chi_Minh
      username: root
      password: root123
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource

security:
  jwt:
    secret-key: oB1Zvsn1261tfh0msDaGCP63l+rYq15F/O+ksyqZWe4qWqHRwvvz5pHs3qgHBhYi

logging:
  level:
    root: INFO
    com.pomina.erpapp: DEBUG
