server:
  port: 8080

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000

    master:
      url: jdbc:mariadb://54.221.149.89:3333/pomina_dev_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Ho_Chi_Minh
      username: root
      password: root123
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource

    slave:
      url: jdbc:mariadb://54.221.149.89:3333/pomina_dev_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Ho_Chi_Minh
      username: root
      password: root123
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          max-active: 50
          max-idle: 10
          min-idle: 2

security:
  jwt:
    access-token-expiration: 900000      # 15 phút
    refresh-token-expiration: 604800000   # 7 ngày
    secret-key: oB1Zvsn1261tfh0msDaGCP63l+rYq15F/O+ksyqZWe4qWqHRwvvz5pHs3qgHBhYi

  encryption:
    secret: zQ4n7A4vFq2EKL+9cUYOLrp+U6NqFpqYcghwNXYc7dI=

nominatim:
  email: minhnam1810@gmail.com
  url: https://nominatim.openstreetmap.org

google:
  maps:
    api-key: AIzaSyDm-BhvvCnWOUKwQeLxRNSRcfesTssRIZI
    geocoding-url: https://maps.googleapis.com/maps/api/geocode/json

vonage:
  api:
    key: c53321d0
    secret: nGXfHZxjpoj0ZNip

logging:
  level:
    root: INFO
    com.pomina.erpapp: DEBUG
